language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-andy' ]; then cd .. && eval "mv $currentfolder generator-andy" && cd generator-andy; fi

